server:
  port: 8052

spring:
  application:
    name: shop-order
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
        port: 8719
      web-context-unify: false